# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Widian Hobby Notes
email: lys2419@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  프로그래밍 중 생긴 문제상황에 대한 대처 및 번역 등록을 위한 블로그. 
  한국어로 검색하는 사람도 양질의 결과를 얻을 수 있는 날이 오기를 기대하면서...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://widian.github.io/" # the base hostname & protocol for your site
twitter_username: lys2419
github_username: widian

# Build settings
markdown: kramdown
